#!/usr/bin/env ruby
require_relative('../spec_helper')

puts SpecWire::Initializer.config.server_url
# add your server path here - should match config/environment.rb
# server_url=http://localhost/~edh/limonade/server.php

